input_string = input('Введите числа, разделенные запятой: ')
print('')
input_string=input_string.replace(' ',',')
print(input_string)
input_string=input_string.replace('/',',')
print(input_string)
input_string=input_string.replace('\\',',')
print(input_string)
input_string=input_string.replace(';',',')
print(input_string)
digit_list = input_string.split(',')
print('спсок чисел: ', digit_list)
digit_list2 = list()
for i in range(len(digit_list)):
    digit_list2.append(int(digit_list[i]))
print('список уникальных чисел: ', set(digit_list))
